~ Salut, je MD @ ousoumane
⚠ Je suis intéressé par ...
✰ J'apprends actuellement ...
-⚠ Je cherche à collaborer sur ...
Comment rejoindre ...

<!---
ousoumane / ousoumane est un dépôt spécial ✨ parce que son `README.md` (ce fichier) apparaît sur votre profil GitHub.
Vous pouvez cliquer sur le lien Aperçu pour jeter un œil à vos modifications.
--->
